Revert "Merge pull request #5 from graingert/patch-1"
This reverts commit 870b32fc02f848ad16f05b1a1958f9a5e0b54361, reversing
changes made to be6e9d6f7376491a7247b8933bd51c90eb2c0e4e.

Defining py3=1 in setup.cfg gave the error:

running bdist_wheel
error: error in setup.cfg: command 'bdist_wheel' has no such option 'py3'